# Generated by Django 2.0.4 on 2018-04-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180417_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='glycemic_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
